#coding= utf-8
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IHelloService.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='IHelloService.proto',
  package='com.manqian.yunke.grpc.demo.api.proto',
  syntax='proto3',
  serialized_pb=_b('\n\x13IHelloService.proto\x12%com.manqian.yunke.grpc.demo.api.proto\"\x1f\n\x10\x46indHelloRequest\x12\x0b\n\x03msg\x18\x01 \x01(\t\"T\n\x11\x46indHelloResponse\x12\x0b\n\x03rtn\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x11\n\tresultMsg\x18\x03 \x01(\t\x12\x12\n\ntotalCount\x18\x04 \x01(\x05\x32\x92\x01\n\rIHelloService\x12\x80\x01\n\tfindHello\x12\x37.com.manqian.yunke.grpc.demo.api.proto.FindHelloRequest\x1a\x38.com.manqian.yunke.grpc.demo.api.proto.FindHelloResponse\"\x00\x42@\n(com.manqian.yunke.grpc.demo.api.protobufB\x12IHelloServiceProtoP\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_FINDHELLOREQUEST = _descriptor.Descriptor(
  name='FindHelloRequest',
  full_name='com.manqian.yunke.grpc.demo.api.proto.FindHelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='com.manqian.yunke.grpc.demo.api.proto.FindHelloRequest.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=93,
)


_FINDHELLORESPONSE = _descriptor.Descriptor(
  name='FindHelloResponse',
  full_name='com.manqian.yunke.grpc.demo.api.proto.FindHelloResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rtn', full_name='com.manqian.yunke.grpc.demo.api.proto.FindHelloResponse.rtn', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='msg', full_name='com.manqian.yunke.grpc.demo.api.proto.FindHelloResponse.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='resultMsg', full_name='com.manqian.yunke.grpc.demo.api.proto.FindHelloResponse.resultMsg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='totalCount', full_name='com.manqian.yunke.grpc.demo.api.proto.FindHelloResponse.totalCount', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=179,
)

DESCRIPTOR.message_types_by_name['FindHelloRequest'] = _FINDHELLOREQUEST
DESCRIPTOR.message_types_by_name['FindHelloResponse'] = _FINDHELLORESPONSE

FindHelloRequest = _reflection.GeneratedProtocolMessageType('FindHelloRequest', (_message.Message,), dict(
  DESCRIPTOR = _FINDHELLOREQUEST,
  __module__ = 'IHelloService_pb2'
  # @@protoc_insertion_point(class_scope:com.manqian.yunke.grpc.demo.api.proto.FindHelloRequest)
  ))
_sym_db.RegisterMessage(FindHelloRequest)

FindHelloResponse = _reflection.GeneratedProtocolMessageType('FindHelloResponse', (_message.Message,), dict(
  DESCRIPTOR = _FINDHELLORESPONSE,
  __module__ = 'IHelloService_pb2'
  # @@protoc_insertion_point(class_scope:com.manqian.yunke.grpc.demo.api.proto.FindHelloResponse)
  ))
_sym_db.RegisterMessage(FindHelloResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n(com.manqian.yunke.grpc.demo.api.protobufB\022IHelloServiceProtoP\001'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class IHelloServiceStub(object):
    """活动服务
    """

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.findHello = channel.unary_unary(
          '/com.manqian.yunke.grpc.demo.api.proto.IHelloService/findHello',
          request_serializer=FindHelloRequest.SerializeToString,
          response_deserializer=FindHelloResponse.FromString,
          )


  class IHelloServiceServicer(object):
    """活动服务
    """

    def findHello(self, request, context):
      """查询Hello
      """
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_IHelloServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'findHello': grpc.unary_unary_rpc_method_handler(
            servicer.findHello,
            request_deserializer=FindHelloRequest.FromString,
            response_serializer=FindHelloResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'com.manqian.yunke.grpc.demo.api.proto.IHelloService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaIHelloServiceServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    """活动服务
    """
    def findHello(self, request, context):
      """查询Hello
      """
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaIHelloServiceStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    """活动服务
    """
    def findHello(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      """查询Hello
      """
      raise NotImplementedError()
    findHello.future = None


  def beta_create_IHelloService_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('com.manqian.yunke.grpc.demo.api.proto.IHelloService', 'findHello'): FindHelloRequest.FromString,
    }
    response_serializers = {
      ('com.manqian.yunke.grpc.demo.api.proto.IHelloService', 'findHello'): FindHelloResponse.SerializeToString,
    }
    method_implementations = {
      ('com.manqian.yunke.grpc.demo.api.proto.IHelloService', 'findHello'): face_utilities.unary_unary_inline(servicer.findHello),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_IHelloService_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('com.manqian.yunke.grpc.demo.api.proto.IHelloService', 'findHello'): FindHelloRequest.SerializeToString,
    }
    response_deserializers = {
      ('com.manqian.yunke.grpc.demo.api.proto.IHelloService', 'findHello'): FindHelloResponse.FromString,
    }
    cardinalities = {
      'findHello': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'com.manqian.yunke.grpc.demo.api.proto.IHelloService', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
