#coding= utf-8
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import IActivityService_pb2 as IActivityService__pb2


class IActivityServiceStub(object):
  """慢钱宝app精彩活动服务api
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetActivityPaging = channel.unary_unary(
        '/app.IActivityService/GetActivityPaging',
        request_serializer=IActivityService__pb2.GetActivityPagingRequest.SerializeToString,
        response_deserializer=IActivityService__pb2.GetActivityPagingResponse.FromString,
        )


class IActivityServiceServicer(object):
  """慢钱宝app精彩活动服务api
  """

  def GetActivityPaging(self, request, context):
    """分页获取精彩活动
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_IActivityServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetActivityPaging': grpc.unary_unary_rpc_method_handler(
          servicer.GetActivityPaging,
          request_deserializer=IActivityService__pb2.GetActivityPagingRequest.FromString,
          response_serializer=IActivityService__pb2.GetActivityPagingResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'app.IActivityService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
