#coding= utf-8
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IAppVersionService.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from app import Entity_pb2 as app_dot_Entity__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='IAppVersionService.proto',
  package='app',
  syntax='proto3',
  serialized_pb=_b('\n\x18IAppVersionService.proto\x12\x03\x61pp\x1a\x10\x61pp/Entity.proto\"A\n\x14GetNewVersionRequest\x12)\n\rrequestHeader\x18\x01 \x01(\x0b\x32\x12.app.RequestHeader\"q\n\x15GetNewVersionResponse\x12+\n\x0eresponseHeader\x18\x01 \x01(\x0b\x32\x13.app.ResponseHeader\x12+\n\x0e\x61ppVersionInfo\x18\x02 \x01(\x0b\x32\x13.app.AppVersionInfo2^\n\x12IAppVersionService\x12H\n\rGetNewVersion\x12\x19.app.GetNewVersionRequest\x1a\x1a.app.GetNewVersionResponse\"\x00\x42\x42\n%com.manqian.bao.grpc.api.protobuf.appB\x17IAppVersionServiceProtoP\x01\x62\x06proto3')
  ,
  dependencies=[app_dot_Entity__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GETNEWVERSIONREQUEST = _descriptor.Descriptor(
  name='GetNewVersionRequest',
  full_name='app.GetNewVersionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requestHeader', full_name='app.GetNewVersionRequest.requestHeader', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=116,
)


_GETNEWVERSIONRESPONSE = _descriptor.Descriptor(
  name='GetNewVersionResponse',
  full_name='app.GetNewVersionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='responseHeader', full_name='app.GetNewVersionResponse.responseHeader', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='appVersionInfo', full_name='app.GetNewVersionResponse.appVersionInfo', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=231,
)

_GETNEWVERSIONREQUEST.fields_by_name['requestHeader'].message_type = app_dot_Entity__pb2._REQUESTHEADER
_GETNEWVERSIONRESPONSE.fields_by_name['responseHeader'].message_type = app_dot_Entity__pb2._RESPONSEHEADER
_GETNEWVERSIONRESPONSE.fields_by_name['appVersionInfo'].message_type = app_dot_Entity__pb2._APPVERSIONINFO
DESCRIPTOR.message_types_by_name['GetNewVersionRequest'] = _GETNEWVERSIONREQUEST
DESCRIPTOR.message_types_by_name['GetNewVersionResponse'] = _GETNEWVERSIONRESPONSE

GetNewVersionRequest = _reflection.GeneratedProtocolMessageType('GetNewVersionRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETNEWVERSIONREQUEST,
  __module__ = 'IAppVersionService_pb2'
  # @@protoc_insertion_point(class_scope:app.GetNewVersionRequest)
  ))
_sym_db.RegisterMessage(GetNewVersionRequest)

GetNewVersionResponse = _reflection.GeneratedProtocolMessageType('GetNewVersionResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETNEWVERSIONRESPONSE,
  __module__ = 'IAppVersionService_pb2'
  # @@protoc_insertion_point(class_scope:app.GetNewVersionResponse)
  ))
_sym_db.RegisterMessage(GetNewVersionResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n%com.manqian.bao.grpc.api.protobuf.appB\027IAppVersionServiceProtoP\001'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class IAppVersionServiceStub(object):
    """慢钱宝app版本服务
    """

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.GetNewVersion = channel.unary_unary(
          '/app.IAppVersionService/GetNewVersion',
          request_serializer=GetNewVersionRequest.SerializeToString,
          response_deserializer=GetNewVersionResponse.FromString,
          )


  class IAppVersionServiceServicer(object):
    """慢钱宝app版本服务
    """

    def GetNewVersion(self, request, context):
      """获取app最新版本
      """
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_IAppVersionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'GetNewVersion': grpc.unary_unary_rpc_method_handler(
            servicer.GetNewVersion,
            request_deserializer=GetNewVersionRequest.FromString,
            response_serializer=GetNewVersionResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'app.IAppVersionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaIAppVersionServiceServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    """慢钱宝app版本服务
    """
    def GetNewVersion(self, request, context):
      """获取app最新版本
      """
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaIAppVersionServiceStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    """慢钱宝app版本服务
    """
    def GetNewVersion(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      """获取app最新版本
      """
      raise NotImplementedError()
    GetNewVersion.future = None


  def beta_create_IAppVersionService_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('app.IAppVersionService', 'GetNewVersion'): GetNewVersionRequest.FromString,
    }
    response_serializers = {
      ('app.IAppVersionService', 'GetNewVersion'): GetNewVersionResponse.SerializeToString,
    }
    method_implementations = {
      ('app.IAppVersionService', 'GetNewVersion'): face_utilities.unary_unary_inline(servicer.GetNewVersion),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_IAppVersionService_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('app.IAppVersionService', 'GetNewVersion'): GetNewVersionRequest.SerializeToString,
    }
    response_deserializers = {
      ('app.IAppVersionService', 'GetNewVersion'): GetNewVersionResponse.FromString,
    }
    cardinalities = {
      'GetNewVersion': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'app.IAppVersionService', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
