#coding= utf-8
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ICouponRecordService.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from app import Entity_pb2 as app_dot_Entity__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ICouponRecordService.proto',
  package='app',
  syntax='proto3',
  serialized_pb=_b('\n\x1aICouponRecordService.proto\x12\x03\x61pp\x1a\x10\x61pp/Entity.proto\"g\n\"GetCouponRecordShowInfoByIdRequest\x12)\n\rrequestHeader\x18\x01 \x01(\x0b\x32\x12.app.RequestHeader\x12\x16\n\x0e\x63ouponRecordId\x18\x02 \x01(\t\"\x84\x01\n\x1c\x43ouponRecordShowInfoResponse\x12+\n\x0eresponseHeader\x18\x01 \x01(\x0b\x32\x13.app.ResponseHeader\x12\x37\n\x14\x63ouponRecordShowInfo\x18\x02 \x01(\x0b\x32\x19.app.CouponRecordShowInfo\"\xd4\x01\n6GetCouponRecordShowInfoByUserIdAndExpiredPagingRequest\x12)\n\rrequestHeader\x18\x01 \x01(\x0b\x32\x12.app.RequestHeader\x12\x12\n\npageNumber\x18\x02 \x01(\x05\x12\x10\n\x08pageSize\x18\x03 \x01(\x05\x12\x0e\n\x06userId\x18\x04 \x01(\t\x12\x0f\n\x07\x65xpired\x18\x05 \x01(\x08\x12(\n\x0b\x63ouponTypes\x18\x06 \x03(\x0e\x32\x13.app.CouponShowType\"\xc8\x01\n7GetCouponRecordShowInfoByUserIdAndExpiredPagingResponse\x12+\n\x0eresponseHeader\x18\x01 \x01(\x0b\x32\x13.app.ResponseHeader\x12#\n\npagingInfo\x18\x02 \x01(\x0b\x32\x0f.app.PagingInfo\x12;\n\x18\x63ouponRecordShowInfoList\x18\x03 \x03(\x0b\x32\x19.app.CouponRecordShowInfo2\xa8\x02\n\x18ICouponRecordShowService\x12\x63\n\x13getCouponRecordById\x12\'.app.GetCouponRecordShowInfoByIdRequest\x1a!.app.CouponRecordShowInfoResponse\"\x00\x12\xa6\x01\n\'getCouponRecordByUserIdAndExpiredPaging\x12;.app.GetCouponRecordShowInfoByUserIdAndExpiredPagingRequest\x1a<.app.GetCouponRecordShowInfoByUserIdAndExpiredPagingResponse\"\x00\x42\x44\n%com.manqian.bao.grpc.api.protobuf.appB\x19ICouponRecordServiceProtoP\x01\x62\x06proto3')
  ,
  dependencies=[app_dot_Entity__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GETCOUPONRECORDSHOWINFOBYIDREQUEST = _descriptor.Descriptor(
  name='GetCouponRecordShowInfoByIdRequest',
  full_name='app.GetCouponRecordShowInfoByIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requestHeader', full_name='app.GetCouponRecordShowInfoByIdRequest.requestHeader', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='couponRecordId', full_name='app.GetCouponRecordShowInfoByIdRequest.couponRecordId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=156,
)


_COUPONRECORDSHOWINFORESPONSE = _descriptor.Descriptor(
  name='CouponRecordShowInfoResponse',
  full_name='app.CouponRecordShowInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='responseHeader', full_name='app.CouponRecordShowInfoResponse.responseHeader', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='couponRecordShowInfo', full_name='app.CouponRecordShowInfoResponse.couponRecordShowInfo', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=291,
)


_GETCOUPONRECORDSHOWINFOBYUSERIDANDEXPIREDPAGINGREQUEST = _descriptor.Descriptor(
  name='GetCouponRecordShowInfoByUserIdAndExpiredPagingRequest',
  full_name='app.GetCouponRecordShowInfoByUserIdAndExpiredPagingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requestHeader', full_name='app.GetCouponRecordShowInfoByUserIdAndExpiredPagingRequest.requestHeader', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pageNumber', full_name='app.GetCouponRecordShowInfoByUserIdAndExpiredPagingRequest.pageNumber', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pageSize', full_name='app.GetCouponRecordShowInfoByUserIdAndExpiredPagingRequest.pageSize', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='userId', full_name='app.GetCouponRecordShowInfoByUserIdAndExpiredPagingRequest.userId', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='expired', full_name='app.GetCouponRecordShowInfoByUserIdAndExpiredPagingRequest.expired', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='couponTypes', full_name='app.GetCouponRecordShowInfoByUserIdAndExpiredPagingRequest.couponTypes', index=5,
      number=6, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=294,
  serialized_end=506,
)


_GETCOUPONRECORDSHOWINFOBYUSERIDANDEXPIREDPAGINGRESPONSE = _descriptor.Descriptor(
  name='GetCouponRecordShowInfoByUserIdAndExpiredPagingResponse',
  full_name='app.GetCouponRecordShowInfoByUserIdAndExpiredPagingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='responseHeader', full_name='app.GetCouponRecordShowInfoByUserIdAndExpiredPagingResponse.responseHeader', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pagingInfo', full_name='app.GetCouponRecordShowInfoByUserIdAndExpiredPagingResponse.pagingInfo', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='couponRecordShowInfoList', full_name='app.GetCouponRecordShowInfoByUserIdAndExpiredPagingResponse.couponRecordShowInfoList', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=509,
  serialized_end=709,
)

_GETCOUPONRECORDSHOWINFOBYIDREQUEST.fields_by_name['requestHeader'].message_type = app_dot_Entity__pb2._REQUESTHEADER
_COUPONRECORDSHOWINFORESPONSE.fields_by_name['responseHeader'].message_type = app_dot_Entity__pb2._RESPONSEHEADER
_COUPONRECORDSHOWINFORESPONSE.fields_by_name['couponRecordShowInfo'].message_type = app_dot_Entity__pb2._COUPONRECORDSHOWINFO
_GETCOUPONRECORDSHOWINFOBYUSERIDANDEXPIREDPAGINGREQUEST.fields_by_name['requestHeader'].message_type = app_dot_Entity__pb2._REQUESTHEADER
_GETCOUPONRECORDSHOWINFOBYUSERIDANDEXPIREDPAGINGREQUEST.fields_by_name['couponTypes'].enum_type = app_dot_Entity__pb2._COUPONSHOWTYPE
_GETCOUPONRECORDSHOWINFOBYUSERIDANDEXPIREDPAGINGRESPONSE.fields_by_name['responseHeader'].message_type = app_dot_Entity__pb2._RESPONSEHEADER
_GETCOUPONRECORDSHOWINFOBYUSERIDANDEXPIREDPAGINGRESPONSE.fields_by_name['pagingInfo'].message_type = app_dot_Entity__pb2._PAGINGINFO
_GETCOUPONRECORDSHOWINFOBYUSERIDANDEXPIREDPAGINGRESPONSE.fields_by_name['couponRecordShowInfoList'].message_type = app_dot_Entity__pb2._COUPONRECORDSHOWINFO
DESCRIPTOR.message_types_by_name['GetCouponRecordShowInfoByIdRequest'] = _GETCOUPONRECORDSHOWINFOBYIDREQUEST
DESCRIPTOR.message_types_by_name['CouponRecordShowInfoResponse'] = _COUPONRECORDSHOWINFORESPONSE
DESCRIPTOR.message_types_by_name['GetCouponRecordShowInfoByUserIdAndExpiredPagingRequest'] = _GETCOUPONRECORDSHOWINFOBYUSERIDANDEXPIREDPAGINGREQUEST
DESCRIPTOR.message_types_by_name['GetCouponRecordShowInfoByUserIdAndExpiredPagingResponse'] = _GETCOUPONRECORDSHOWINFOBYUSERIDANDEXPIREDPAGINGRESPONSE

GetCouponRecordShowInfoByIdRequest = _reflection.GeneratedProtocolMessageType('GetCouponRecordShowInfoByIdRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETCOUPONRECORDSHOWINFOBYIDREQUEST,
  __module__ = 'ICouponRecordService_pb2'
  # @@protoc_insertion_point(class_scope:app.GetCouponRecordShowInfoByIdRequest)
  ))
_sym_db.RegisterMessage(GetCouponRecordShowInfoByIdRequest)

CouponRecordShowInfoResponse = _reflection.GeneratedProtocolMessageType('CouponRecordShowInfoResponse', (_message.Message,), dict(
  DESCRIPTOR = _COUPONRECORDSHOWINFORESPONSE,
  __module__ = 'ICouponRecordService_pb2'
  # @@protoc_insertion_point(class_scope:app.CouponRecordShowInfoResponse)
  ))
_sym_db.RegisterMessage(CouponRecordShowInfoResponse)

GetCouponRecordShowInfoByUserIdAndExpiredPagingRequest = _reflection.GeneratedProtocolMessageType('GetCouponRecordShowInfoByUserIdAndExpiredPagingRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETCOUPONRECORDSHOWINFOBYUSERIDANDEXPIREDPAGINGREQUEST,
  __module__ = 'ICouponRecordService_pb2'
  # @@protoc_insertion_point(class_scope:app.GetCouponRecordShowInfoByUserIdAndExpiredPagingRequest)
  ))
_sym_db.RegisterMessage(GetCouponRecordShowInfoByUserIdAndExpiredPagingRequest)

GetCouponRecordShowInfoByUserIdAndExpiredPagingResponse = _reflection.GeneratedProtocolMessageType('GetCouponRecordShowInfoByUserIdAndExpiredPagingResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETCOUPONRECORDSHOWINFOBYUSERIDANDEXPIREDPAGINGRESPONSE,
  __module__ = 'ICouponRecordService_pb2'
  # @@protoc_insertion_point(class_scope:app.GetCouponRecordShowInfoByUserIdAndExpiredPagingResponse)
  ))
_sym_db.RegisterMessage(GetCouponRecordShowInfoByUserIdAndExpiredPagingResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n%com.manqian.bao.grpc.api.protobuf.appB\031ICouponRecordServiceProtoP\001'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class ICouponRecordShowServiceStub(object):
    """慢钱宝app精彩服务api
    """

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.getCouponRecordById = channel.unary_unary(
          '/app.ICouponRecordShowService/getCouponRecordById',
          request_serializer=GetCouponRecordShowInfoByIdRequest.SerializeToString,
          response_deserializer=CouponRecordShowInfoResponse.FromString,
          )
      self.getCouponRecordByUserIdAndExpiredPaging = channel.unary_unary(
          '/app.ICouponRecordShowService/getCouponRecordByUserIdAndExpiredPaging',
          request_serializer=GetCouponRecordShowInfoByUserIdAndExpiredPagingRequest.SerializeToString,
          response_deserializer=GetCouponRecordShowInfoByUserIdAndExpiredPagingResponse.FromString,
          )


  class ICouponRecordShowServiceServicer(object):
    """慢钱宝app精彩服务api
    """

    def getCouponRecordById(self, request, context):
      """getCouponRecordById
      """
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def getCouponRecordByUserIdAndExpiredPaging(self, request, context):
      """根据用户id和是否失效以及类型获取优惠券记录页
      """
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_ICouponRecordShowServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'getCouponRecordById': grpc.unary_unary_rpc_method_handler(
            servicer.getCouponRecordById,
            request_deserializer=GetCouponRecordShowInfoByIdRequest.FromString,
            response_serializer=CouponRecordShowInfoResponse.SerializeToString,
        ),
        'getCouponRecordByUserIdAndExpiredPaging': grpc.unary_unary_rpc_method_handler(
            servicer.getCouponRecordByUserIdAndExpiredPaging,
            request_deserializer=GetCouponRecordShowInfoByUserIdAndExpiredPagingRequest.FromString,
            response_serializer=GetCouponRecordShowInfoByUserIdAndExpiredPagingResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'app.ICouponRecordShowService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaICouponRecordShowServiceServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    """慢钱宝app精彩服务api
    """
    def getCouponRecordById(self, request, context):
      """getCouponRecordById
      """
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def getCouponRecordByUserIdAndExpiredPaging(self, request, context):
      """根据用户id和是否失效以及类型获取优惠券记录页
      """
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaICouponRecordShowServiceStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    """慢钱宝app精彩服务api
    """
    def getCouponRecordById(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      """getCouponRecordById
      """
      raise NotImplementedError()
    getCouponRecordById.future = None
    def getCouponRecordByUserIdAndExpiredPaging(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      """根据用户id和是否失效以及类型获取优惠券记录页
      """
      raise NotImplementedError()
    getCouponRecordByUserIdAndExpiredPaging.future = None


  def beta_create_ICouponRecordShowService_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('app.ICouponRecordShowService', 'getCouponRecordById'): GetCouponRecordShowInfoByIdRequest.FromString,
      ('app.ICouponRecordShowService', 'getCouponRecordByUserIdAndExpiredPaging'): GetCouponRecordShowInfoByUserIdAndExpiredPagingRequest.FromString,
    }
    response_serializers = {
      ('app.ICouponRecordShowService', 'getCouponRecordById'): CouponRecordShowInfoResponse.SerializeToString,
      ('app.ICouponRecordShowService', 'getCouponRecordByUserIdAndExpiredPaging'): GetCouponRecordShowInfoByUserIdAndExpiredPagingResponse.SerializeToString,
    }
    method_implementations = {
      ('app.ICouponRecordShowService', 'getCouponRecordById'): face_utilities.unary_unary_inline(servicer.getCouponRecordById),
      ('app.ICouponRecordShowService', 'getCouponRecordByUserIdAndExpiredPaging'): face_utilities.unary_unary_inline(servicer.getCouponRecordByUserIdAndExpiredPaging),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_ICouponRecordShowService_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('app.ICouponRecordShowService', 'getCouponRecordById'): GetCouponRecordShowInfoByIdRequest.SerializeToString,
      ('app.ICouponRecordShowService', 'getCouponRecordByUserIdAndExpiredPaging'): GetCouponRecordShowInfoByUserIdAndExpiredPagingRequest.SerializeToString,
    }
    response_deserializers = {
      ('app.ICouponRecordShowService', 'getCouponRecordById'): CouponRecordShowInfoResponse.FromString,
      ('app.ICouponRecordShowService', 'getCouponRecordByUserIdAndExpiredPaging'): GetCouponRecordShowInfoByUserIdAndExpiredPagingResponse.FromString,
    }
    cardinalities = {
      'getCouponRecordById': cardinality.Cardinality.UNARY_UNARY,
      'getCouponRecordByUserIdAndExpiredPaging': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'app.ICouponRecordShowService', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
