#coding= utf-8
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IIndexService.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from app import Entity_pb2 as app_dot_Entity__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='IIndexService.proto',
  package='app',
  syntax='proto3',
  serialized_pb=_b('\n\x13IIndexService.proto\x12\x03\x61pp\x1a\x10\x61pp/Entity.proto\"@\n\x13GetIndexInfoRequest\x12)\n\rrequestHeader\x18\x01 \x01(\x0b\x32\x12.app.RequestHeader\"\xc0\x02\n\x14GetIndexInfoResponse\x12+\n\x0eresponseHeader\x18\x01 \x01(\x0b\x32\x13.app.ResponseHeader\x12\'\n\x0e\x62\x61nnerInfoList\x18\x02 \x03(\x0b\x32\x0f.app.BannerInfo\x12+\n\x10\x61\x63tivityInfoList\x18\x03 \x03(\x0b\x32\x11.app.ActivityInfo\x12\x37\n\x16RecommendPlateInfoList\x18\x04 \x03(\x0b\x32\x17.app.RecommendPlateInfo\x12\x39\n\x15\x65xperienceProductInfo\x18\x05 \x01(\x0b\x32\x1a.app.ExperienceProductInfo\x12\x31\n\x11newbieProductInfo\x18\x06 \x01(\x0b\x32\x16.app.NewbieProductInfo2V\n\rIIndexService\x12\x45\n\x0cGetIndexInfo\x12\x18.app.GetIndexInfoRequest\x1a\x19.app.GetIndexInfoResponse\"\x00\x42=\n%com.manqian.bao.grpc.api.protobuf.appB\x12IIndexServiceProtoP\x01\x62\x06proto3')
  ,
  dependencies=[app_dot_Entity__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GETINDEXINFOREQUEST = _descriptor.Descriptor(
  name='GetIndexInfoRequest',
  full_name='app.GetIndexInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requestHeader', full_name='app.GetIndexInfoRequest.requestHeader', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=110,
)


_GETINDEXINFORESPONSE = _descriptor.Descriptor(
  name='GetIndexInfoResponse',
  full_name='app.GetIndexInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='responseHeader', full_name='app.GetIndexInfoResponse.responseHeader', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bannerInfoList', full_name='app.GetIndexInfoResponse.bannerInfoList', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='activityInfoList', full_name='app.GetIndexInfoResponse.activityInfoList', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='RecommendPlateInfoList', full_name='app.GetIndexInfoResponse.RecommendPlateInfoList', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='experienceProductInfo', full_name='app.GetIndexInfoResponse.experienceProductInfo', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='newbieProductInfo', full_name='app.GetIndexInfoResponse.newbieProductInfo', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=433,
)

_GETINDEXINFOREQUEST.fields_by_name['requestHeader'].message_type = app_dot_Entity__pb2._REQUESTHEADER
_GETINDEXINFORESPONSE.fields_by_name['responseHeader'].message_type = app_dot_Entity__pb2._RESPONSEHEADER
_GETINDEXINFORESPONSE.fields_by_name['bannerInfoList'].message_type = app_dot_Entity__pb2._BANNERINFO
_GETINDEXINFORESPONSE.fields_by_name['activityInfoList'].message_type = app_dot_Entity__pb2._ACTIVITYINFO
_GETINDEXINFORESPONSE.fields_by_name['RecommendPlateInfoList'].message_type = app_dot_Entity__pb2._RECOMMENDPLATEINFO
_GETINDEXINFORESPONSE.fields_by_name['experienceProductInfo'].message_type = app_dot_Entity__pb2._EXPERIENCEPRODUCTINFO
_GETINDEXINFORESPONSE.fields_by_name['newbieProductInfo'].message_type = app_dot_Entity__pb2._NEWBIEPRODUCTINFO
DESCRIPTOR.message_types_by_name['GetIndexInfoRequest'] = _GETINDEXINFOREQUEST
DESCRIPTOR.message_types_by_name['GetIndexInfoResponse'] = _GETINDEXINFORESPONSE

GetIndexInfoRequest = _reflection.GeneratedProtocolMessageType('GetIndexInfoRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETINDEXINFOREQUEST,
  __module__ = 'IIndexService_pb2'
  # @@protoc_insertion_point(class_scope:app.GetIndexInfoRequest)
  ))
_sym_db.RegisterMessage(GetIndexInfoRequest)

GetIndexInfoResponse = _reflection.GeneratedProtocolMessageType('GetIndexInfoResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETINDEXINFORESPONSE,
  __module__ = 'IIndexService_pb2'
  # @@protoc_insertion_point(class_scope:app.GetIndexInfoResponse)
  ))
_sym_db.RegisterMessage(GetIndexInfoResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n%com.manqian.bao.grpc.api.protobuf.appB\022IIndexServiceProtoP\001'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class IIndexServiceStub(object):
    """慢钱宝app发现服务
    """

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.GetIndexInfo = channel.unary_unary(
          '/app.IIndexService/GetIndexInfo',
          request_serializer=GetIndexInfoRequest.SerializeToString,
          response_deserializer=GetIndexInfoResponse.FromString,
          )


  class IIndexServiceServicer(object):
    """慢钱宝app发现服务
    """

    def GetIndexInfo(self, request, context):
      """获取首页信息
      """
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_IIndexServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'GetIndexInfo': grpc.unary_unary_rpc_method_handler(
            servicer.GetIndexInfo,
            request_deserializer=GetIndexInfoRequest.FromString,
            response_serializer=GetIndexInfoResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'app.IIndexService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaIIndexServiceServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    """慢钱宝app发现服务
    """
    def GetIndexInfo(self, request, context):
      """获取首页信息
      """
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaIIndexServiceStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    """慢钱宝app发现服务
    """
    def GetIndexInfo(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      """获取首页信息
      """
      raise NotImplementedError()
    GetIndexInfo.future = None


  def beta_create_IIndexService_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('app.IIndexService', 'GetIndexInfo'): GetIndexInfoRequest.FromString,
    }
    response_serializers = {
      ('app.IIndexService', 'GetIndexInfo'): GetIndexInfoResponse.SerializeToString,
    }
    method_implementations = {
      ('app.IIndexService', 'GetIndexInfo'): face_utilities.unary_unary_inline(servicer.GetIndexInfo),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_IIndexService_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('app.IIndexService', 'GetIndexInfo'): GetIndexInfoRequest.SerializeToString,
    }
    response_deserializers = {
      ('app.IIndexService', 'GetIndexInfo'): GetIndexInfoResponse.FromString,
    }
    cardinalities = {
      'GetIndexInfo': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'app.IIndexService', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
