#coding= utf-8
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import IIndexService_pb2 as IIndexService__pb2


class IIndexServiceStub(object):
  """慢钱宝app发现服务
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetIndexInfo = channel.unary_unary(
        '/app.IIndexService/GetIndexInfo',
        request_serializer=IIndexService__pb2.GetIndexInfoRequest.SerializeToString,
        response_deserializer=IIndexService__pb2.GetIndexInfoResponse.FromString,
        )


class IIndexServiceServicer(object):
  """慢钱宝app发现服务
  """

  def GetIndexInfo(self, request, context):
    """获取首页信息
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_IIndexServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetIndexInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetIndexInfo,
          request_deserializer=IIndexService__pb2.GetIndexInfoRequest.FromString,
          response_serializer=IIndexService__pb2.GetIndexInfoResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'app.IIndexService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
