#coding= utf-8
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import IMessageService_pb2 as IMessageService__pb2


class IMessageServiceStub(object):
  """慢钱宝app消息服务
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetMessagePaging = channel.unary_unary(
        '/app.IMessageService/GetMessagePaging',
        request_serializer=IMessageService__pb2.GetMessagePagingRequest.SerializeToString,
        response_deserializer=IMessageService__pb2.GetMessagePagingResponse.FromString,
        )
    self.GetUnreadMessageCount = channel.unary_unary(
        '/app.IMessageService/GetUnreadMessageCount',
        request_serializer=IMessageService__pb2.GetUnreadMessageCountRequest.SerializeToString,
        response_deserializer=IMessageService__pb2.GetUnreadMessageCountResponse.FromString,
        )


class IMessageServiceServicer(object):
  """慢钱宝app消息服务
  """

  def GetMessagePaging(self, request, context):
    """*
    获取消息列表
    注意： 第一次获取的未读消息，状态未读；
    第二次获取时候，消息便是已读状态，因为在第一次获取后会自动更新读取状态。
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUnreadMessageCount(self, request, context):
    """获取未读消息的条数
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_IMessageServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetMessagePaging': grpc.unary_unary_rpc_method_handler(
          servicer.GetMessagePaging,
          request_deserializer=IMessageService__pb2.GetMessagePagingRequest.FromString,
          response_serializer=IMessageService__pb2.GetMessagePagingResponse.SerializeToString,
      ),
      'GetUnreadMessageCount': grpc.unary_unary_rpc_method_handler(
          servicer.GetUnreadMessageCount,
          request_deserializer=IMessageService__pb2.GetUnreadMessageCountRequest.FromString,
          response_serializer=IMessageService__pb2.GetUnreadMessageCountResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'app.IMessageService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
