#coding= utf-8
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IMessageService.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from app import Entity_pb2 as app_dot_Entity__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='IMessageService.proto',
  package='app',
  syntax='proto3',
  serialized_pb=_b('\n\x15IMessageService.proto\x12\x03\x61pp\x1a\x10\x61pp/Entity.proto\"X\n\x17GetMessagePagingRequest\x12)\n\rrequestHeader\x18\x01 \x01(\x0b\x32\x12.app.RequestHeader\x12\x12\n\npageNumber\x18\x02 \x01(\x05\"\x97\x01\n\x18GetMessagePagingResponse\x12+\n\x0eresponseHeader\x18\x01 \x01(\x0b\x32\x13.app.ResponseHeader\x12#\n\npagingInfo\x18\x02 \x01(\x0b\x32\x0f.app.PagingInfo\x12)\n\x0fmessageInfoList\x18\x03 \x03(\x0b\x32\x10.app.MessageInfo\"I\n\x1cGetUnreadMessageCountRequest\x12)\n\rrequestHeader\x18\x01 \x01(\x0b\x32\x12.app.RequestHeader\"[\n\x1dGetUnreadMessageCountResponse\x12+\n\x0eresponseHeader\x18\x01 \x01(\x0b\x32\x13.app.ResponseHeader\x12\r\n\x05\x63ount\x18\x02 \x01(\x03\x32\xc6\x01\n\x0fIMessageService\x12Q\n\x10GetMessagePaging\x12\x1c.app.GetMessagePagingRequest\x1a\x1d.app.GetMessagePagingResponse\"\x00\x12`\n\x15GetUnreadMessageCount\x12!.app.GetUnreadMessageCountRequest\x1a\".app.GetUnreadMessageCountResponse\"\x00\x42?\n%com.manqian.bao.grpc.api.protobuf.appB\x14IMessageServiceProtoP\x01\x62\x06proto3')
  ,
  dependencies=[app_dot_Entity__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GETMESSAGEPAGINGREQUEST = _descriptor.Descriptor(
  name='GetMessagePagingRequest',
  full_name='app.GetMessagePagingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requestHeader', full_name='app.GetMessagePagingRequest.requestHeader', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pageNumber', full_name='app.GetMessagePagingRequest.pageNumber', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=136,
)


_GETMESSAGEPAGINGRESPONSE = _descriptor.Descriptor(
  name='GetMessagePagingResponse',
  full_name='app.GetMessagePagingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='responseHeader', full_name='app.GetMessagePagingResponse.responseHeader', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pagingInfo', full_name='app.GetMessagePagingResponse.pagingInfo', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='messageInfoList', full_name='app.GetMessagePagingResponse.messageInfoList', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=290,
)


_GETUNREADMESSAGECOUNTREQUEST = _descriptor.Descriptor(
  name='GetUnreadMessageCountRequest',
  full_name='app.GetUnreadMessageCountRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requestHeader', full_name='app.GetUnreadMessageCountRequest.requestHeader', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=292,
  serialized_end=365,
)


_GETUNREADMESSAGECOUNTRESPONSE = _descriptor.Descriptor(
  name='GetUnreadMessageCountResponse',
  full_name='app.GetUnreadMessageCountResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='responseHeader', full_name='app.GetUnreadMessageCountResponse.responseHeader', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='app.GetUnreadMessageCountResponse.count', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=367,
  serialized_end=458,
)

_GETMESSAGEPAGINGREQUEST.fields_by_name['requestHeader'].message_type = app_dot_Entity__pb2._REQUESTHEADER
_GETMESSAGEPAGINGRESPONSE.fields_by_name['responseHeader'].message_type = app_dot_Entity__pb2._RESPONSEHEADER
_GETMESSAGEPAGINGRESPONSE.fields_by_name['pagingInfo'].message_type = app_dot_Entity__pb2._PAGINGINFO
_GETMESSAGEPAGINGRESPONSE.fields_by_name['messageInfoList'].message_type = app_dot_Entity__pb2._MESSAGEINFO
_GETUNREADMESSAGECOUNTREQUEST.fields_by_name['requestHeader'].message_type = app_dot_Entity__pb2._REQUESTHEADER
_GETUNREADMESSAGECOUNTRESPONSE.fields_by_name['responseHeader'].message_type = app_dot_Entity__pb2._RESPONSEHEADER
DESCRIPTOR.message_types_by_name['GetMessagePagingRequest'] = _GETMESSAGEPAGINGREQUEST
DESCRIPTOR.message_types_by_name['GetMessagePagingResponse'] = _GETMESSAGEPAGINGRESPONSE
DESCRIPTOR.message_types_by_name['GetUnreadMessageCountRequest'] = _GETUNREADMESSAGECOUNTREQUEST
DESCRIPTOR.message_types_by_name['GetUnreadMessageCountResponse'] = _GETUNREADMESSAGECOUNTRESPONSE

GetMessagePagingRequest = _reflection.GeneratedProtocolMessageType('GetMessagePagingRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETMESSAGEPAGINGREQUEST,
  __module__ = 'IMessageService_pb2'
  # @@protoc_insertion_point(class_scope:app.GetMessagePagingRequest)
  ))
_sym_db.RegisterMessage(GetMessagePagingRequest)

GetMessagePagingResponse = _reflection.GeneratedProtocolMessageType('GetMessagePagingResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETMESSAGEPAGINGRESPONSE,
  __module__ = 'IMessageService_pb2'
  # @@protoc_insertion_point(class_scope:app.GetMessagePagingResponse)
  ))
_sym_db.RegisterMessage(GetMessagePagingResponse)

GetUnreadMessageCountRequest = _reflection.GeneratedProtocolMessageType('GetUnreadMessageCountRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETUNREADMESSAGECOUNTREQUEST,
  __module__ = 'IMessageService_pb2'
  # @@protoc_insertion_point(class_scope:app.GetUnreadMessageCountRequest)
  ))
_sym_db.RegisterMessage(GetUnreadMessageCountRequest)

GetUnreadMessageCountResponse = _reflection.GeneratedProtocolMessageType('GetUnreadMessageCountResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETUNREADMESSAGECOUNTRESPONSE,
  __module__ = 'IMessageService_pb2'
  # @@protoc_insertion_point(class_scope:app.GetUnreadMessageCountResponse)
  ))
_sym_db.RegisterMessage(GetUnreadMessageCountResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n%com.manqian.bao.grpc.api.protobuf.appB\024IMessageServiceProtoP\001'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class IMessageServiceStub(object):
    """慢钱宝app消息服务
    """

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.GetMessagePaging = channel.unary_unary(
          '/app.IMessageService/GetMessagePaging',
          request_serializer=GetMessagePagingRequest.SerializeToString,
          response_deserializer=GetMessagePagingResponse.FromString,
          )
      self.GetUnreadMessageCount = channel.unary_unary(
          '/app.IMessageService/GetUnreadMessageCount',
          request_serializer=GetUnreadMessageCountRequest.SerializeToString,
          response_deserializer=GetUnreadMessageCountResponse.FromString,
          )


  class IMessageServiceServicer(object):
    """慢钱宝app消息服务
    """

    def GetMessagePaging(self, request, context):
      """*
      获取消息列表
      注意： 第一次获取的未读消息，状态未读；
      第二次获取时候，消息便是已读状态，因为在第一次获取后会自动更新读取状态。
      """
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def GetUnreadMessageCount(self, request, context):
      """获取未读消息的条数
      """
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_IMessageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'GetMessagePaging': grpc.unary_unary_rpc_method_handler(
            servicer.GetMessagePaging,
            request_deserializer=GetMessagePagingRequest.FromString,
            response_serializer=GetMessagePagingResponse.SerializeToString,
        ),
        'GetUnreadMessageCount': grpc.unary_unary_rpc_method_handler(
            servicer.GetUnreadMessageCount,
            request_deserializer=GetUnreadMessageCountRequest.FromString,
            response_serializer=GetUnreadMessageCountResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'app.IMessageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaIMessageServiceServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    """慢钱宝app消息服务
    """
    def GetMessagePaging(self, request, context):
      """*
      获取消息列表
      注意： 第一次获取的未读消息，状态未读；
      第二次获取时候，消息便是已读状态，因为在第一次获取后会自动更新读取状态。
      """
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def GetUnreadMessageCount(self, request, context):
      """获取未读消息的条数
      """
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaIMessageServiceStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    """慢钱宝app消息服务
    """
    def GetMessagePaging(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      """*
      获取消息列表
      注意： 第一次获取的未读消息，状态未读；
      第二次获取时候，消息便是已读状态，因为在第一次获取后会自动更新读取状态。
      """
      raise NotImplementedError()
    GetMessagePaging.future = None
    def GetUnreadMessageCount(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      """获取未读消息的条数
      """
      raise NotImplementedError()
    GetUnreadMessageCount.future = None


  def beta_create_IMessageService_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('app.IMessageService', 'GetMessagePaging'): GetMessagePagingRequest.FromString,
      ('app.IMessageService', 'GetUnreadMessageCount'): GetUnreadMessageCountRequest.FromString,
    }
    response_serializers = {
      ('app.IMessageService', 'GetMessagePaging'): GetMessagePagingResponse.SerializeToString,
      ('app.IMessageService', 'GetUnreadMessageCount'): GetUnreadMessageCountResponse.SerializeToString,
    }
    method_implementations = {
      ('app.IMessageService', 'GetMessagePaging'): face_utilities.unary_unary_inline(servicer.GetMessagePaging),
      ('app.IMessageService', 'GetUnreadMessageCount'): face_utilities.unary_unary_inline(servicer.GetUnreadMessageCount),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_IMessageService_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('app.IMessageService', 'GetMessagePaging'): GetMessagePagingRequest.SerializeToString,
      ('app.IMessageService', 'GetUnreadMessageCount'): GetUnreadMessageCountRequest.SerializeToString,
    }
    response_deserializers = {
      ('app.IMessageService', 'GetMessagePaging'): GetMessagePagingResponse.FromString,
      ('app.IMessageService', 'GetUnreadMessageCount'): GetUnreadMessageCountResponse.FromString,
    }
    cardinalities = {
      'GetMessagePaging': cardinality.Cardinality.UNARY_UNARY,
      'GetUnreadMessageCount': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'app.IMessageService', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
