#coding= utf-8
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IOrderService.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from app import Entity_pb2 as app_dot_Entity__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='IOrderService.proto',
  package='app',
  syntax='proto3',
  serialized_pb=_b('\n\x13IOrderService.proto\x12\x03\x61pp\x1a\x10\x61pp/Entity.proto\"\x7f\n\x17GetMyOrderPagingRequest\x12)\n\rrequestHeader\x18\x01 \x01(\x0b\x32\x12.app.RequestHeader\x12\x12\n\npageNumber\x18\x02 \x01(\x05\x12%\n\x0borderStatus\x18\x03 \x03(\x0e\x32\x10.app.OrderStatus\"\x93\x01\n\x18GetMyOrderPagingResponse\x12+\n\x0eresponseHeader\x18\x01 \x01(\x0b\x32\x13.app.ResponseHeader\x12#\n\npagingInfo\x18\x02 \x01(\x0b\x32\x0f.app.PagingInfo\x12%\n\rorderInfoList\x18\x03 \x03(\x0b\x32\x0e.app.OrderInfo\"W\n\x17GetMyOrderDetailRequest\x12)\n\rrequestHeader\x18\x01 \x01(\x0b\x32\x12.app.RequestHeader\x12\x11\n\torderCode\x18\x02 \x01(\t\"v\n\x18GetMyOrderDetailResponse\x12+\n\x0eresponseHeader\x18\x01 \x01(\x0b\x32\x13.app.ResponseHeader\x12-\n\x0forderDetailInfo\x18\x02 \x01(\x0b\x32\x14.app.OrderDetailInfo2\xb5\x01\n\rIOrderService\x12Q\n\x10GetMyOrderPaging\x12\x1c.app.GetMyOrderPagingRequest\x1a\x1d.app.GetMyOrderPagingResponse\"\x00\x12Q\n\x10GetMyOrderDetail\x12\x1c.app.GetMyOrderDetailRequest\x1a\x1d.app.GetMyOrderDetailResponse\"\x00\x42=\n%com.manqian.bao.grpc.api.protobuf.appB\x12IOrderServiceProtoP\x01\x62\x06proto3')
  ,
  dependencies=[app_dot_Entity__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GETMYORDERPAGINGREQUEST = _descriptor.Descriptor(
  name='GetMyOrderPagingRequest',
  full_name='app.GetMyOrderPagingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requestHeader', full_name='app.GetMyOrderPagingRequest.requestHeader', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pageNumber', full_name='app.GetMyOrderPagingRequest.pageNumber', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='orderStatus', full_name='app.GetMyOrderPagingRequest.orderStatus', index=2,
      number=3, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=173,
)


_GETMYORDERPAGINGRESPONSE = _descriptor.Descriptor(
  name='GetMyOrderPagingResponse',
  full_name='app.GetMyOrderPagingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='responseHeader', full_name='app.GetMyOrderPagingResponse.responseHeader', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pagingInfo', full_name='app.GetMyOrderPagingResponse.pagingInfo', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='orderInfoList', full_name='app.GetMyOrderPagingResponse.orderInfoList', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=323,
)


_GETMYORDERDETAILREQUEST = _descriptor.Descriptor(
  name='GetMyOrderDetailRequest',
  full_name='app.GetMyOrderDetailRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requestHeader', full_name='app.GetMyOrderDetailRequest.requestHeader', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='orderCode', full_name='app.GetMyOrderDetailRequest.orderCode', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=325,
  serialized_end=412,
)


_GETMYORDERDETAILRESPONSE = _descriptor.Descriptor(
  name='GetMyOrderDetailResponse',
  full_name='app.GetMyOrderDetailResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='responseHeader', full_name='app.GetMyOrderDetailResponse.responseHeader', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='orderDetailInfo', full_name='app.GetMyOrderDetailResponse.orderDetailInfo', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=414,
  serialized_end=532,
)

_GETMYORDERPAGINGREQUEST.fields_by_name['requestHeader'].message_type = app_dot_Entity__pb2._REQUESTHEADER
_GETMYORDERPAGINGREQUEST.fields_by_name['orderStatus'].enum_type = app_dot_Entity__pb2._ORDERSTATUS
_GETMYORDERPAGINGRESPONSE.fields_by_name['responseHeader'].message_type = app_dot_Entity__pb2._RESPONSEHEADER
_GETMYORDERPAGINGRESPONSE.fields_by_name['pagingInfo'].message_type = app_dot_Entity__pb2._PAGINGINFO
_GETMYORDERPAGINGRESPONSE.fields_by_name['orderInfoList'].message_type = app_dot_Entity__pb2._ORDERINFO
_GETMYORDERDETAILREQUEST.fields_by_name['requestHeader'].message_type = app_dot_Entity__pb2._REQUESTHEADER
_GETMYORDERDETAILRESPONSE.fields_by_name['responseHeader'].message_type = app_dot_Entity__pb2._RESPONSEHEADER
_GETMYORDERDETAILRESPONSE.fields_by_name['orderDetailInfo'].message_type = app_dot_Entity__pb2._ORDERDETAILINFO
DESCRIPTOR.message_types_by_name['GetMyOrderPagingRequest'] = _GETMYORDERPAGINGREQUEST
DESCRIPTOR.message_types_by_name['GetMyOrderPagingResponse'] = _GETMYORDERPAGINGRESPONSE
DESCRIPTOR.message_types_by_name['GetMyOrderDetailRequest'] = _GETMYORDERDETAILREQUEST
DESCRIPTOR.message_types_by_name['GetMyOrderDetailResponse'] = _GETMYORDERDETAILRESPONSE

GetMyOrderPagingRequest = _reflection.GeneratedProtocolMessageType('GetMyOrderPagingRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETMYORDERPAGINGREQUEST,
  __module__ = 'IOrderService_pb2'
  # @@protoc_insertion_point(class_scope:app.GetMyOrderPagingRequest)
  ))
_sym_db.RegisterMessage(GetMyOrderPagingRequest)

GetMyOrderPagingResponse = _reflection.GeneratedProtocolMessageType('GetMyOrderPagingResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETMYORDERPAGINGRESPONSE,
  __module__ = 'IOrderService_pb2'
  # @@protoc_insertion_point(class_scope:app.GetMyOrderPagingResponse)
  ))
_sym_db.RegisterMessage(GetMyOrderPagingResponse)

GetMyOrderDetailRequest = _reflection.GeneratedProtocolMessageType('GetMyOrderDetailRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETMYORDERDETAILREQUEST,
  __module__ = 'IOrderService_pb2'
  # @@protoc_insertion_point(class_scope:app.GetMyOrderDetailRequest)
  ))
_sym_db.RegisterMessage(GetMyOrderDetailRequest)

GetMyOrderDetailResponse = _reflection.GeneratedProtocolMessageType('GetMyOrderDetailResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETMYORDERDETAILRESPONSE,
  __module__ = 'IOrderService_pb2'
  # @@protoc_insertion_point(class_scope:app.GetMyOrderDetailResponse)
  ))
_sym_db.RegisterMessage(GetMyOrderDetailResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n%com.manqian.bao.grpc.api.protobuf.appB\022IOrderServiceProtoP\001'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class IOrderServiceStub(object):
    """慢钱宝app订单/投资服务
    """

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.GetMyOrderPaging = channel.unary_unary(
          '/app.IOrderService/GetMyOrderPaging',
          request_serializer=GetMyOrderPagingRequest.SerializeToString,
          response_deserializer=GetMyOrderPagingResponse.FromString,
          )
      self.GetMyOrderDetail = channel.unary_unary(
          '/app.IOrderService/GetMyOrderDetail',
          request_serializer=GetMyOrderDetailRequest.SerializeToString,
          response_deserializer=GetMyOrderDetailResponse.FromString,
          )


  class IOrderServiceServicer(object):
    """慢钱宝app订单/投资服务
    """

    def GetMyOrderPaging(self, request, context):
      """获取我的订单列表数据
      """
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def GetMyOrderDetail(self, request, context):
      """获取我的订单详情
      """
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_IOrderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'GetMyOrderPaging': grpc.unary_unary_rpc_method_handler(
            servicer.GetMyOrderPaging,
            request_deserializer=GetMyOrderPagingRequest.FromString,
            response_serializer=GetMyOrderPagingResponse.SerializeToString,
        ),
        'GetMyOrderDetail': grpc.unary_unary_rpc_method_handler(
            servicer.GetMyOrderDetail,
            request_deserializer=GetMyOrderDetailRequest.FromString,
            response_serializer=GetMyOrderDetailResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'app.IOrderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaIOrderServiceServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    """慢钱宝app订单/投资服务
    """
    def GetMyOrderPaging(self, request, context):
      """获取我的订单列表数据
      """
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def GetMyOrderDetail(self, request, context):
      """获取我的订单详情
      """
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaIOrderServiceStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    """慢钱宝app订单/投资服务
    """
    def GetMyOrderPaging(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      """获取我的订单列表数据
      """
      raise NotImplementedError()
    GetMyOrderPaging.future = None
    def GetMyOrderDetail(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      """获取我的订单详情
      """
      raise NotImplementedError()
    GetMyOrderDetail.future = None


  def beta_create_IOrderService_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('app.IOrderService', 'GetMyOrderDetail'): GetMyOrderDetailRequest.FromString,
      ('app.IOrderService', 'GetMyOrderPaging'): GetMyOrderPagingRequest.FromString,
    }
    response_serializers = {
      ('app.IOrderService', 'GetMyOrderDetail'): GetMyOrderDetailResponse.SerializeToString,
      ('app.IOrderService', 'GetMyOrderPaging'): GetMyOrderPagingResponse.SerializeToString,
    }
    method_implementations = {
      ('app.IOrderService', 'GetMyOrderDetail'): face_utilities.unary_unary_inline(servicer.GetMyOrderDetail),
      ('app.IOrderService', 'GetMyOrderPaging'): face_utilities.unary_unary_inline(servicer.GetMyOrderPaging),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_IOrderService_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('app.IOrderService', 'GetMyOrderDetail'): GetMyOrderDetailRequest.SerializeToString,
      ('app.IOrderService', 'GetMyOrderPaging'): GetMyOrderPagingRequest.SerializeToString,
    }
    response_deserializers = {
      ('app.IOrderService', 'GetMyOrderDetail'): GetMyOrderDetailResponse.FromString,
      ('app.IOrderService', 'GetMyOrderPaging'): GetMyOrderPagingResponse.FromString,
    }
    cardinalities = {
      'GetMyOrderDetail': cardinality.Cardinality.UNARY_UNARY,
      'GetMyOrderPaging': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'app.IOrderService', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
