#coding= utf-8
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import IOrderService_pb2 as IOrderService__pb2


class IOrderServiceStub(object):
  """慢钱宝app订单/投资服务
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetMyOrderPaging = channel.unary_unary(
        '/app.IOrderService/GetMyOrderPaging',
        request_serializer=IOrderService__pb2.GetMyOrderPagingRequest.SerializeToString,
        response_deserializer=IOrderService__pb2.GetMyOrderPagingResponse.FromString,
        )
    self.GetMyOrderDetail = channel.unary_unary(
        '/app.IOrderService/GetMyOrderDetail',
        request_serializer=IOrderService__pb2.GetMyOrderDetailRequest.SerializeToString,
        response_deserializer=IOrderService__pb2.GetMyOrderDetailResponse.FromString,
        )


class IOrderServiceServicer(object):
  """慢钱宝app订单/投资服务
  """
  def GetMyOrderPaging(self, request, context):
    """获取我的订单列表数据
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMyOrderDetail(self, request, context):
    """获取我的订单详情
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_IOrderServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetMyOrderPaging': grpc.unary_unary_rpc_method_handler(
          servicer.GetMyOrderPaging,
          request_deserializer=IOrderService__pb2.GetMyOrderPagingRequest.FromString,
          response_serializer=IOrderService__pb2.GetMyOrderPagingResponse.SerializeToString,
      ),
      'GetMyOrderDetail': grpc.unary_unary_rpc_method_handler(
          servicer.GetMyOrderDetail,
          request_deserializer=IOrderService__pb2.GetMyOrderDetailRequest.FromString,
          response_serializer=IOrderService__pb2.GetMyOrderDetailResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'app.IOrderService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
