# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-25 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.IntegerField()),
                ('title', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=40)),
                ('method', models.CharField(max_length=10)),
                ('url', models.CharField(max_length=30)),
                ('params', models.CharField(max_length=50)),
                ('ex_result', models.CharField(max_length=100)),
            ],
        ),
    ]
