# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-16 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0005_auto_20170616_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='level',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
