# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-22 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0009_auto_20170621_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='interface_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
