# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-22 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0010_report_interface_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.IntegerField()),
                ('interface_name', models.CharField(max_length=20)),
                ('func_name', models.CharField(max_length=20)),
                ('interface_result', models.CharField(max_length=10)),
                ('case_detail', models.CharField(max_length=10000)),
            ],
        ),
    ]
