# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-22 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0012_auto_20170622_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_detail',
            name='report_id',
            field=models.CharField(max_length=40),
        ),
    ]
