# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-15 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0003_auto_20170531_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=20)),
                ('service_name', models.CharField(max_length=30)),
                ('func', models.CharField(max_length=20)),
                ('developer', models.CharField(max_length=20)),
                ('notes', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=40)),
                ('leader', models.CharField(max_length=10)),
                ('remark', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='testcase',
            name='ex_result',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
