# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-16 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0004_auto_20170615_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='desc',
            new_name='level',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='case_id',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='method',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='url',
        ),
        migrations.AddField(
            model_name='testcase',
            name='interface_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='tester',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
