# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-21 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0008_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='details',
        ),
        migrations.AddField(
            model_name='report',
            name='detail_list',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
