# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-28 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0014_auto_20170623_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report_detail',
            name='interface_name',
        ),
        migrations.AddField(
            model_name='report_detail',
            name='interface_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
