# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-28 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0015_auto_20170628_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_detail',
            name='interface_name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
