# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-29 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0016_report_detail_interface_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='precondition',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='params',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
